export const SITE_SELECT_COLUMNS = [
  "id",
  "site_id",
  "site",
  "operadora_origem",
  "tipo_elemento",
  "tecnologia",
  "municipio",
  "estado",
  "uf",
  "regional",
  "endereco",
  "status_normalizado",
  "status",
  "projeto",
  "tipo_site",
  "detentor_infra",
  "tipo_infra",
  "latitude",
  "longitude",
  "populacao",
  "altura",
  "geo_score",
  "risco",
  "station_id",
  "operadora_classificada",
  "ori_score",
  "ori_risk",
  "data_importacao",
  "arquivo_origem",
];

export const SITE_SELECT = SITE_SELECT_COLUMNS.join(",");
